source 'https://rubygems.org'

ruby '2.0.0'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use sqlite3 as the database for Active Record
gem 'pg'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# solr search service
gem 'sunspot_rails'
gem 'sunspot_solr'

gem "sorcery"

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

gem 'activerecord-import', '>= 0.4.0'
group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :development, :test do
  gem 'rspec-rails'
  gem 'ZenTest'
  gem 'factory_girl_rails'
  gem 'debugger'
  gem "json_spec", "~> 1.1.1"
  #gem 'database_cleaner'
end

group :development, :test do
      gem 'railroady'
end

# Authorization library for Ruby on Rails
gem "cancan"

